version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - ${MYSQL_PATH}:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
       - ${APP_CODE_PATH_HOST}:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped

volumes:
    postgres:
    pgadmin: